### ISSUE TITLE
Updating the LR at every step 

### ISSUE THREAD

**Issue by pclucas14** [facebookresearch/vissl#219]
## 📚 VISSL Documentation

Hi, 

 I am trying to do a linear warmup with a cosine schedule. I followed the instructions [here](https://github.com/facebookresearch/vissl/blob/a5c973bce3cd778a17a0045dd3ee2f56ef247624/vissl/optimizers/param_scheduler/README.md). While I specified `update_interval=step`, it seems the learning rate update only happens every epoch when I look at the TB plots. 
![Screen Shot 2021-03-05 at 10 21 52 AM](https://user-images.githubusercontent.com/20862882/110135630-baf63580-7d9c-11eb-89cf-cdb15366e575.png)

This is most likely me not understanding how to use the scheduling args, so any documentation related to this would help. I looked [here](https://github.com/facebookresearch/vissl/blob/a5c973bce3cd778a17a0045dd3ee2f56ef247624/vissl/optimizers/param_scheduler/README.md) and on the default config but could not find an answer.

Here is my current optimization config 
```
  OPTIMIZER:
      name: adam
      lr: 0.0001
      weight_decay: 0
      num_epochs: 50
      clip_grad_norm: 1
      head_optimizer_params:
        use_different_lr: False
        use_different_wd: False
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: false
            base_value: 0.3
            base_lr_batch_size: 256
          name: composite
          schedulers:
            - name: linear
              start_value: 1e-5
              end_value: 1e-4
            - name: cosine
              start_value: 1e-4
              end_value: 0.
              # wave_type: half
              # restart_interval_length: 0.5
              wave_type: full
              is_adaptive: True
              restart_interval_length: 0.334
          interval_scaling: [rescaled, fixed]
          update_interval: step
          lengths: [0.05, 0.95]                 # 100ep # how to split between warmup and cos. anneal?
```

(here is what I am trying do to, for reference)
![Screen Shot 2021-03-05 at 10 20 04 AM](https://user-images.githubusercontent.com/20862882/110135553-a6b23880-7d9c-11eb-9739-7d89e5c5fb1c.png)
