### ISSUE TITLE
Obtain validation losses with SimCLR's fully unsupervised pre-training?

### ISSUE THREAD

**Issue by ycm** [facebookresearch/vissl#323]
## Question about applying fully unsupervised pre-training with VISSL

I have a dataset of images, split into two classes. My directory structure looks like:
```
data/
├── train/
│   ├── class0/
|   |   └── *.png
│   └── class1/
|       └── *.png
|
└── val/
    ├── class0/
    |   └── *.png
    └── class1/
        └── *.png
```

I'm currently running `run_distributed_engines.py` with a custom YAML config file, and my dataset catalog looks like this:
```
{"data_data": {"train": ["/data/train", "<unused>"], "val": ["/data/val", "<unused>"]}}
```
Inside the yaml, I set `TEST_MODEL: False`.

But I've noticed that the `val` folder (`/data/val`) doesn't actually get used. On Tensorboard, I do not see validation loss, only training loss.

So I have two questions:

1. **After pre-training, how do I retrieve the pretrained SimCLR weights for another downstream task?** I think it is stored in `checkpoint['classy_state_dict']['base_model']['model']['trunk']`, but I want to make sure this is the case.
2. **Is it possible to use a validation set during pre-training?** I'm confused as to how one can apply checkpoint selection or early stopping without a validation set.

I tried to following the [Getting Started guide](https://github.com/facebookresearch/vissl/blob/master/GETTING_STARTED.md) and the related [Colab tutorial](https://colab.research.google.com/drive/1CCuZ50BN99JcOB6VEPytVi_i2tSMd7A3#scrollTo=KPGCiTsXZeW3) but those two sources seem a little too terse for my purposes.

Any help would be appreciated, thank you.

**Comment by QuentinDuval** [comment]
Hi @ycm,

You should indeed be able t access the SimCLR weights in `checkpoint['classy_state_dict']['base_model']['model']['trunk']`. This is the best option if you want to transfer to a downstream task not supported in VISSL.

If you want to try it on one of the VISSL benchmarks, you can avoid that entirely (for instance if you want to do a classification benchmark on any dataset) and just pass the following option to the configuration:
`config.MODEL.WEIGHTS_INIT.PARAMS_FILE=/path/to/simclr/model_final_checkpoint_phase999.torch`

Here is an example for Imagenet linear classification:

```
python tools/run_distributed_engines.py \
      config=benchmark/linear_image_classification/imagenet1k/eval_resnet_8gpu_transfer_in1k_linear \
      config.MODEL.WEIGHTS_INIT.PARAMS_FILE=<my_weights.torch>
```

Regarding the validation loss during SimCLR pre-training, I never actually tried it before, and so I tried it, but unsuccessfully.

I enabled some options in the default configuration file for SimCLR (`configs/config/pretrain/simclr/simclr_8node_resnet.yaml`, is the one you are using?) and modified the configuration to add a test set:

```
TEST:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenette_160_folder]
      BATCHSIZE_PER_REPLICA: 128
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 128
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 1.0
        - name: ImgPilGaussianBlur
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: simclr_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenette_160/
      DROP_LAST: True
```

As well as enabling it the test set: `config.TEST_MODEL=true`.

Unfortunately, although it makes SimCLR run on the validation set, it does not output any losses (I think we are supposed to use the `config.METERS` but in that case the meter should be the loss and I am not quite sure how to do this.

I think @prigoyal could have some insights I am missing, but I think we need to make a small fix to enable this.

@prigoyal  what do you think?
