### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by Jeffkang-94** [facebookresearch/vissl#564]
## Instructions To Reproduce the Issue:
`Dino` configuration contains the parameter named `MLP_DIM` which looks like being adjustable by the user. But actually, it is hard coded. See the line here https://github.com/facebookresearch/vissl/blob/4ca0ae351b1030742132179bffd9b8640fd5a6f0/vissl/models/trunks/vision_transformer.py#L149-L155 

I wanted to adjust the `mlp_ratio` or size of `mlp_dim` through the configuration as I've met several OOM issues because of the huge dataset,
```yaml
  MODEL:
    TRUNK:
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 512
        PATCH_SIZE: 16
        NUM_LAYERS: 3
        NUM_HEADS: 12
        HIDDEN_DIM: 192 
        # MLP_DIM: 768 # Not Used!
        CLASSIFIER: token
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1
```

But it seems that the mlp_dim is not adjustable through the configuration. Apart from it, it also raises some confusion for the user who wants to change the size of mlp dimension. 

## Expected behavior:
To be specific, with the configuration 
```yaml
MODEL:
    TRUNK:
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        HIDDEN_DIM: 384
        MLP_DIM: 768 # Not Used!
```
`mlp` is supposed to have 
```bash
mlp dim : Mlp(
  (fc1): Linear(in_features=384, out_features=768, bias=True)
  (act): GELU()
  (fc2): Linear(in_features=768, out_features=384, bias=True)
  (drop): Dropout(p=0, inplace=False)
)
```
but actually it has

```bash
mlp dim : Mlp(
  (fc1): Linear(in_features=384, out_features=1536, bias=True)
  (act): GELU()
  (fc2): Linear(in_features=1536, out_features=384, bias=True)
  (drop): Dropout(p=0, inplace=False)
)
```
because of the pre-defined value `mlp_ratio=4.0` here https://github.com/facebookresearch/vissl/blob/4ca0ae351b1030742132179bffd9b8640fd5a6f0/vissl/models/trunks/vision_transformer.py#L262
